language: r
cache: packages
sudo: true

r_github_packages:
  - jimhester/covr

r:
  - release
  - devel

r_check_args: "--as-cran"

after_success:
  - Rscript -e 'covr::codecov(token="61b4bc87-9f95-4b70-b0ad-0bf8bce07df1")'
