language: r
cache: packages
os:
  - linux
  #- osx
  #- windows

r_github_packages:
  - jimhester/covr
  - ropensci/taxa

r:
  - oldrel
  - release
  - devel

r_check_args: "--as-cran"

after_success:
  - Rscript -e 'covr::codecov(token="61b4bc87-9f95-4b70-b0ad-0bf8bce07df1")'
